export const ZOOM_SPEED = 1.1;

export const SNAPPING_TOLERANCE = 10;

export const RULES_COLOR = "#456";

export const BOUNDING_AREA_PADDING = 5;

export const SELECTION_BOX_COLOR = "#5ab";
export const SELECTION_BOX_SQUARE_LENGTH = 5;

export const CONTACT_SIZE = 6;
export const CONTACT_LINE_WIDTH = 1.65;

export const ELECTRIC_CONTACT_COLOR = "#c66";
export const PNEUMATIC_CONTACT_COLOR = "#6c6";

export const ELECTRIC_CONNECTION_COLOR = ELECTRIC_CONTACT_COLOR;
export const PNEUMATIC_CONNECTION_COLOR = PNEUMATIC_CONTACT_COLOR;
